server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 10290238
    key-store-type: PKCS12
    key-alias: tomcat


spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://ilitsoobe.cvmu8s0ma26p.ap-northeast-2.rds.amazonaws.com:3306/groom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ilitsoobe
      password: ilitsoobe)123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  mvc:
    path-match:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      querydsl: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE

jwt:
  secret-key: jwjdkalkjdsklsakdQWEFSDA3eas23dsakfaskd
